version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - external-nw

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_test:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    networks:
      - external-nw

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "poetry", "run", "python", "apihub/run_server.py" ]
    ports:
      - "5000:5000"
    environment:
      - OUT_KIND=LREDIS
      - OUT_REDIS=redis://redis:6379/1
      - OUT_NAMESPACE=api
      - REDIS=redis://redis:6379/1
      - DB_URI=postgresql://dbuser:dbpass@postgres/test
      - DEBUG=TRUE
      - RELOAD=TRUE
      - PYTHONPATH=/app
    links:
      - redis
      - postgres
    networks:
      - external-nw
    volumes:
      - .:/app

  master:
    build:
      context: .
      dockerfile: Dockerfile-locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfiles:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089

  worker:
    build:
      context: .
      dockerfile: Dockerfile-locust
    #    image: locustio/locust
    volumes:
      - ./locustfiles:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master


volumes:
  postgres_test:

networks:
  external-nw:
