version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_test:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=test
    ports:
      - "5432:5432"

volumes:
  postgres_test:
