apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apihub-result
  name: apihub-result
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apihub-result
  template:
    metadata:
      labels:
        app: apihub-result
    spec:
      containers:
      - command:
        - poetry
        - run
        - apihub_result
        envFrom:
        - configMapRef:
            name: pipeline-config
        - configMapRef:
            name: result-config
        image: meganews.azurecr.io/apihub:v0.1.2a6
        imagePullPolicy: IfNotPresent
        name: result
        ports:
        - containerPort: 8000
          name: http-metrics
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
