apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apihub-server
  name: apihub-server
  namespace: apihub
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apihub-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apihub-server
    spec:
      containers:
      - command:
        - poetry
        - run
        - apihub_server
        envFrom:
        - configMapRef:
            name: pipeline-config
        - configMapRef:
            name: server-config
        image: meganews.azurecr.io/meganews/apihub
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
        name: server
        ports:
        - containerPort: 5000
          name: http-metrics
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
